version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: meadow
      MONGO_INITDB_ROOT_PASSWORD: meadow_su
    # volumes:
    #   - ./database/config/mongod.conf:/etc/mongo/mongod.conf
    #   - ./database/data:/data/db
    #   - ./database/log:/var/log/mongodb
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: meadow
      ME_CONFIG_BASICAUTH_PASSWORD: meadow_su
      ME_CONFIG_MONGODB_ADMINUSERNAME: meadow
      ME_CONFIG_MONGODB_ADMINPASSWORD: meadow_su
      ME_CONFIG_MONGODB_URL: mongodb://meadow:meadow_su@mongo:27017/